rayon = 5
hauteur = 6
aire_cylindre = 2 * 3.14 * rayon * (rayon + hauteur)
print(aire_cylindre)